apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

namePrefix: dev-

namespace: dev

patches:
  - path: service-dev.yaml
    target:
      kind: Service
      name: nginx-with-random-data
  - path: deployment-dev.yaml
    target:
      kind: Deployment
      name: nginx-with-random-data
  - path: configmap-dev.yaml
    target:
      kind: ConfigMap
      name: configmap-html