apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: prod-

namespace: prod

patches:
  - path: service-prod.yaml
    target:
      kind: Service
      name: nginx-with-random-data
  - path: deployment-prod.yaml
    target:
      kind: Deployment
      name: nginx-with-random-data
  - path: configmap-prod.yaml
    target:
      kind: ConfigMap
      name: configmap-html
  - path: namespace-prod.yaml
    target:
      kind: Namespace
      name: prod