apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace-staging.yaml 

namePrefix: staging-

namespace: staging

patches:
  - path: service-staging.yaml
    target:
      kind: Service
      name: nginx-with-random-data
  - path: deployment-staging.yaml
    target:
      kind: Deployment
      name: nginx-with-random-data
  - path: configmap-staging.yaml
    target:
      kind: ConfigMap
      name: configmap-html