apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-shared-data
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Mi
    volumeMode: Filesystem
    storageClassName: "standard"